#!/bin/bash
# Generate PNG icons from SVG using ImageMagick (if available)
# Or use this as a guide to create PNGs manually

echo "🎨 GrindTime Icon Generation Guide"
echo "=================================="
echo ""
echo "Chrome extensions work best with PNG icons."
echo "SVG icons are supported but can cause issues with notifications."
echo ""
echo "To create PNG icons, you have several options:"
echo ""
echo "Option 1: Use ImageMagick (if installed)"
echo "  convert icons/icon16.svg icons/icon16.png"
echo "  convert icons/icon48.svg icons/icon48.png"
echo "  convert icons/icon128.svg icons/icon128.png"
echo ""
echo "Option 2: Use Inkscape (if installed)"
echo "  inkscape icons/icon16.svg --export-filename=icons/icon16.png -w 16 -h 16"
echo "  inkscape icons/icon48.svg --export-filename=icons/icon48.png -w 48 -h 48"
echo "  inkscape icons/icon128.svg --export-filename=icons/icon128.png -w 128 -h 128"
echo ""
echo "Option 3: Use Online Converter"
echo "  1. Go to: https://cloudconvert.com/svg-to-png"
echo "  2. Upload each SVG file"
echo "  3. Download the PNG versions"
echo "  4. Save them in the icons/ folder"
echo ""
echo "Option 4: Use a Graphic Editor"
echo "  - Open SVG in GIMP, Photoshop, Figma, or any image editor"
echo "  - Export as PNG at the correct sizes (16x16, 48x48, 128x128)"
echo ""
echo "Option 5: Use Node.js script (included below)"
echo ""
echo "For now, the extension will work without PNG icons."
echo "Chrome will use default icons for notifications."
echo ""
